### ISSUE TITLE
Mass channel MODE with -lk throws error

### ISSUE THREAD

**Issue by metaglot** [martynsmith/node-irc#177]
I get this when my client is in a channel and someone sets mode -lk

(It might be worth noting that i have changed my irc.js to use Array.splice instead of delete as in Fix deletion of array elements.)
                    
/usr/share/adafruit/webide/node_modules/irc/lib/irc.js:638                                                                                 
                    throw err;                                                                                                             
                          ^                                                                                                                
TypeError: Cannot read property 'length' of undefined                                                                                      
    at /usr/share/adafruit/webide/node_modules/irc/lib/irc.js:248:41                                                                       
    at Array.forEach (native)                                                                                                              
    at Client.<anonymous> (/usr/share/adafruit/webide/node_modules/irc/lib/irc.js:226:26)                                                  
    at Client.EventEmitter.emit (events.js:117:20)                                                                                         
    at /usr/share/adafruit/webide/node_modules/irc/lib/irc.js:635:22                                                                       
    at Array.forEach (native)                                                                                                              
    at Socket.<anonymous> (/usr/share/adafruit/webide/node_modules/irc/lib/irc.js:632:15)                                                  
    at Socket.EventEmitter.emit (events.js:95:17)                                                                                          
    at Socket.<anonymous> (_stream_readable.js:736:14)                                                                                     
    at Socket.EventEmitter.emit (events.js:92:17)

**Comment by ward** [comment]
This was fixed by PR #351, I confirmed locally that 0.4.1 still has the bug while 0.5.0 does not any more.
