### ISSUE TITLE
Bot crashes on mode +q-o

### ISSUE THREAD

**Issue by fwilson42** [martynsmith/node-irc#221]
I did this in a channel:
```
-- | Mode #channel [+q-o someone!*@* someone] by me
```

Only to find this:
```
<-- | mynodebot (~polybots@some/hostname) has quit (Remote host closed the connection)   
<-- | anothernodebot (~nodebot@some/hostname) has quit (Remote host closed the connection)            
```

They appear to quit like this:
```
2014-02-17T20:24:59.085752+00:00 app[irc.1]:                     throw err;
2014-02-17T20:24:59.085752+00:00 app[irc.1]:                           ^
2014-02-17T20:24:59.085443+00:00 app[irc.1]: /app/node_modules/irc/lib/irc.js:637
2014-02-17T20:24:59.089936+00:00 app[irc.1]: TypeError: Cannot call method 'replace' of undefined
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at /app/node_modules/irc/lib/irc.js:239:71
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Array.forEach (native)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Client.<anonymous> (/app/node_modules/irc/lib/irc.js:226:26)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Client.EventEmitter.emit (events.js:95:17)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at /app/node_modules/irc/lib/irc.js:634:22
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Array.forEach (native)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Socket.<anonymous> (/app/node_modules/irc/lib/irc.js:631:15)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Socket.<anonymous> (_stream_readable.js:746:14)
2014-02-17T20:24:59.090294+00:00 app[irc.1]:     at Socket.EventEmitter.emit (events.js:92:17)
2014-02-17T20:24:59.089936+00:00 app[irc.1]:     at Socket.EventEmitter.emit (events.js:95:17)
```

This is on freenode (i.e. +q == quiet).

**Comment by jirwin** [comment]
This should be fixed by #351.
