### ISSUE TITLE
EOF Error - Any ideas?

### ISSUE THREAD

**Issue by Hardware-Hacks** [martynsmith/node-irc#284]
Any ideas why I keep seeing Client-EOF quit with the following in the logs:

```
^[[35m[2015-01-10 11:02:12.788] [FATAL] p3negram - TypeError: Cannot read property 'key' of undefined
    at Client.<anonymous> (/home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:431:46)
    at Client.emit (events.js:107:17)
    at /home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:669:22
    at Array.forEach (native)
    at Socket.<anonymous> (/home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:666:15)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Socket.Readable.push (_stream_readable.js:125:10)
    at TCP.onread (net.js:514:20)
error: Forever detected script exited with code: 1
```

**Comment by apeiron** [comment]
Not without seeing the code you're using, no.

**Comment by apeiron** [comment]
@Hardware-Hacks can you provide code that reproduces this, along with the version of node-irc?

**Comment by Hardware-Hacks** [comment]
Hi,

I'm seeing the following error:

```
[2015-01-24 14:21:49.560] [FATAL] p3negram - TypeError: Cannot read property 'indexOf' of undefined
    at /home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:269:52
    at Array.forEach (native)
    at Client.<anonymous> (/home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:256:26)
    at Client.emit (events.js:107:17)
    at iterator (/home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:753:22)
    at Array.forEach (native)
    at Socket.<anonymous> (/home/munkee/Programs/NodeApps/node-p3negram/node_modules/irc/lib/irc.js:749:15)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Socket.Readable.push (_stream_readable.js:125:10)

```
Ill check my version

**Comment by ward** [comment]
The second error seems different from the first. The second one looks like it is the same issue as found in bugs #177 and #233 so can be ignored since it was fixed by PR #351 .
