### ISSUE TITLE
Version 0.3.8 failed while using hubot-irc

### ISSUE THREAD

**Issue by nandub** [martynsmith/node-irc#289]
When using 0.3.8 I get the following error:

```
[Sat Jan 10 2015 22:15:56 GMT-0600 (CST)] ERROR TypeError: Cannot read property 'length' of undefined
  at Client._updateMaxLineLength (/Users/fortiz/development/nodedev/myhubot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:1024:64)
  at Client.<anonymous> (/Users/fortiz/development/nodedev/myhubot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:222:22)
  at Client.emit (events.js:95:17)
  at iterator (/Users/fortiz/development/nodedev/myhubot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:753:22)
  at Array.forEach (native)
  at Socket.<anonymous> (/Users/fortiz/development/nodedev/myhubot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:749:15)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```
Probably because of this change https://github.com/martynsmith/node-irc/commit/9481a7188d13de8b36b56a332977e5694cc131d7 made to _updateMaxLineLength prototype.

**Comment by apeiron** [comment]
This is a known bug (see #283) that we'll be fixing shortly.

**Comment by nandub** [comment]
Sorry about that.
