### ISSUE TITLE
Issue installing on OS X Mavericks

### ISSUE THREAD

**Issue by austinhyde** [martynsmith/node-irc#308]
I'm not sure if this occurs on other versions of OS X, but at least on Mavericks, I got the following error while installing:

```
$ npm install irc
-
> node-icu-charset-detector@0.0.7 install [redacted]/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:5:10: fatal error: 'unicode/ucsdet.h' file not found
#include <unicode/ucsdet.h>
         ^
1 error generated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd [redacted]/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> iconv@2.1.4 install [redacted]/node_modules/irc/node_modules/iconv
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/iconv.node
  SOLINK_MODULE(target) Release/iconv.node: Finished
npm WARN optional dep failed, continuing node-icu-charset-detector@0.0.7
irc@0.3.9 node_modules/irc
├── ansi-color@0.2.1
├── irc-colors@1.1.0 (hashish@0.0.4)
└── iconv@2.1.4 (nan@1.1.2)
```

I was able to resolve these errors by

* Installing the full XCode app (not just the command line tools), and running it once to accept the EULA
* `brew install icu4c`
* `ln -s /usr/local/Cellar/icu4c/54.1/include/* /usr/local/include/`
* `npm install irc` again

Someone familiar with the involved tools/dependencies should verify this is the correct solution, and the install documentation should be updated.

**Comment by apeiron** [comment]
It actually installed, as you can see (the `irc@0.3.9 node_modules/irc` bit means it installed). The README specifies that there are optional dependencies that should be installed.

**Comment by apeiron** [comment]
To be clear, iconv and node-icu-charset-detector are [optional dependencies](https://github.com/martynsmith/node-irc/blob/master/package.json#L39). This is specified in the README, and I've made it clearer.

**Comment by buley** [comment]
It no longer seems to be getting to the install phase before failing on this optional depdendency.

~~~

[copilot] npm install

> node-icu-charset-detector@0.1.4 install /Users/buley/Code/copilot/node_modules/node-icu-charset-detector
> node-gyp rebuild

  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:10: fatal error: 'unicode/ucsdet.h' file not found
#include <unicode/ucsdet.h>
         ^
1 error generated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/buley/Code/copilot/node_modules/node-icu-charset-detector
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:node-icu-charset-detector@0.1.4 node-icu-charset-detector@0.1.4 install: `node-gyp rebuild`
npm WARN install:node-icu-charset-detector@0.1.4 Exit status 1
npm WARN EPACKAGEJSON copilot@1.0.0 No description
npm WARN EPACKAGEJSON copilot@1.0.0 No repository field.

**Comment by cuongleqq** [comment]
I have the same problem
@masochist I checked my node_modules folder and there is no `irc` installed.
I also try the solution above by @austinhyde but it doesn't work. I need to try more to have the .h files.
