### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ReidandKat** [martynsmith/node-irc#325]
Can someone please assist me with this. I have a simple irc client that sends messages to visitors via socket.io

This error seems to happen completely randomly:

C:\Program Files\nodejs\node_modules\irc\lib\parse_message.js:39
    message.command = match[1];
                           ^
TypeError: Cannot read property '1' of null
    at parseMessage (C:\Program Files\nodejs\node_modules\irc\lib\parse_message.js:39:28)
    at iterator (C:\Program Files\nodejs\node_modules\irc\lib\irc.js:753:27)
    at Array.forEach (native)
    at Socket.<anonymous> (C:\Program Files\nodejs\node_modules\irc\lib\irc.js:752:15)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

**Comment by aivot-on** [comment]
It happens when server sends an empty line.
PR https://github.com/martynsmith/node-irc/pull/318 fixed the problem for me.

**Comment by ReidandKat** [comment]
When will the fix be pushed to npm?

**Comment by saltire** [comment]
Second this; an NPM update would be great.

I've found this issue occurs when the server sends newlines as `\r\n` and the packets split up the `\r` and the `\n`. The `\n` gets interpreted as an empty line, causing a crash. It'd be nice to have #318 in the NPM release.

Thanks for this package, btw!

**Comment by Shilo** [comment]
+1

**Comment by Czzzzzzzzz** [comment]
I also encountered this problem today. It happened when NPM install
