### ISSUE TITLE
Random crash after rpl_luserunknown

### ISSUE THREAD

**Issue by clux** [martynsmith/node-irc#342]
Got this crash while starting an irc bot today:

4 Apr 12:26:18 - SEND: NICK wolfram
4 Apr 12:26:18 - SEND: USER alpha 8 * wolfram
4 Apr 12:26:18 - SEND: PONG 2918491847
4 Apr 12:26:27 - Unhandled message: { prefix: 'underworld1.no.quakenet.org',
  server: 'underworld1.no.quakenet.org',
  command: 'rpl_luserunknown',
  rawCommand: '253',
  commandType: 'reply',
  args: [ 'wolfram', '3', 'unknown connection(s)' ] }
4 Apr 12:26:27 - GOT NOTICE from the server: "Highest connection count: 4854 (4853 clients)"

/home/clux/repos/irc-stream/node_modules/irc/lib/parse_message.js:39
    message.command = match[1];
                           ^
TypeError: Cannot read property '1' of null
    at parseMessage (/home/clux/repos/irc-stream/node_modules/irc/lib/parse_message.js:39:28)
    at iterator (/home/clux/repos/irc-stream/node_modules/irc/lib/irc.js:753:27)
    at Array.forEach (native)
    at Socket.<anonymous> (/home/clux/repos/irc-stream/node_modules/irc/lib/irc.js:752:15)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)

I am binding to the error event, and judging by the debug log, it is after that. irc@0.3.9
Maybe some corner case in your regex?

**Comment by brentnk** [comment]
Pull https://github.com/martynsmith/node-irc/pull/318 addresses this issue.  I don't think that the fix has been pushed to npm though so you'll have to install directly from Github for the latest version.
`"irc": "git://github.com/martynsmith/node-irc"` should do it.

**Comment by clux** [comment]
Ok thank you :)

**Comment by jirwin** [comment]
#318 was merged and published. Closing this.
