### ISSUE TITLE
Error client.say(nick, "record\\w3xp\\random\\wins");

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#369]
i want whisper ``record\w3xp\random\wins``
so my code is
``client.say(nick, "record\\w3xp\\random\\wins");``

but its give me error
```
/home/csonline/anonprophet/node_modules/irc/lib/irc.js:748
                        throw err;
                              ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Client.emit (events.js:87:13)
    at Client.<anonymous> (/home/csonline/anonprophet/node_modules/irc/lib/irc.js:590:26)
    at Client.emit (events.js:107:17)
    at iterator (/home/csonline/anonprophet/node_modules/irc/lib/irc.js:745:26)
    at Array.forEach (native)
    at Socket.<anonymous> (/home/csonline/anonprophet/node_modules/irc/lib/irc.js:740:15)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by anonprophet** [comment]
anyone pliz can fix this ?
my bot often use that command.

**Comment by Kegsay** [comment]
Please read https://github.com/martynsmith/node-irc#help---it-keeps-crashing

You need to add a listener for `error`.

**Comment by DingGGu** [comment]
client.send("set", "record\\w3xp\\random\\wins");

**Comment by jirwin** [comment]
Closing this for now. If you are still having trouble with this, please report back with the actual error you see.
