### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by anonprophet** [martynsmith/node-irc#400]
```
root@dota:/home/bot# npm install irc
npm http GET https://registry.npmjs.org/irc
npm http 304 https://registry.npmjs.org/irc
npm http GET https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/node-icu-charset-detector/0.1.0
npm http GET https://registry.npmjs.org/ansi-color/0.2.1
npm http GET https://registry.npmjs.org/irc-colors
npm http 304 https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/ansi-color/0.2.1
npm http 304 https://registry.npmjs.org/irc-colors
npm http 304 https://registry.npmjs.org/node-icu-charset-detector/0.1.0
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/hashish
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/hashish
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/traverse

> node-icu-charset-detector@0.1.0 install /home/bot/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

make: Entering directory `/home/bot/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:28: fatal error: unicode/ucsdet.h: No such file or directory
 #include <unicode/ucsdet.h>
                            ^
compilation terminated.

> iconv@2.1.10 install /home/bot/node_modules/irc/node_modules/iconv
> node-gyp rebuild

make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory `/home/bot/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bot/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing node-icu-charset-detector@0.1.0
make: Entering directory `/home/bot/node_modules/irc/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory `/home/bot/node_modules/irc/node_modules/iconv/build'
irc@0.3.12 node_modules/irc
├── ansi-color@0.2.1
├── irc-colors@1.2.0 (hashish@0.0.4)
└── iconv@2.1.10 (nan@2.0.8)
root@dota:/home/bot# npm install irc
npm http GET https://registry.npmjs.org/irc
npm http 304 https://registry.npmjs.org/irc
npm http GET https://registry.npmjs.org/ansi-color/0.2.1
npm http GET https://registry.npmjs.org/irc-colors
npm http GET https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/node-icu-charset-detector/0.1.0
npm http 304 https://registry.npmjs.org/ansi-color/0.2.1
npm http 304 https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/node-icu-charset-detector/0.1.0
npm http 304 https://registry.npmjs.org/irc-colors
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/hashish
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/hashish
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/traverse

> node-icu-charset-detector@0.1.0 install /home/bot/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

make: Entering directory `/home/bot/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:28: fatal error: unicode/ucsdet.h: No such file or directory
 #include <unicode/ucsdet.h>
                            ^
compilation terminated.

> iconv@2.1.10 install /home/bot/node_modules/irc/node_modules/iconv
> node-gyp rebuild

make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory `/home/bot/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bot/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing node-icu-charset-detector@0.1.0
make: Entering directory `/home/bot/node_modules/irc/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory `/home/bot/node_modules/irc/node_modules/iconv/build'
irc@0.3.12 node_modules/irc
├── ansi-color@0.2.1
├── irc-colors@1.2.0 (hashish@0.0.4)
└── iconv@2.1.10 (nan@2.0.8)
root@dota:/home/bot#
```

where im missing?

**Comment by jirwin** [comment]
`iconv` is an optional dependency for detecting charsets. You may need to install extra dependencies for it to compile. 

The library doesn't need it to run though. Note `npm WARN optional dep failed`.

You might need to run something like `sudo apt-get -y install libicu-dev` on your system.

P.S. I wouldn't run your bot as root :)
