### ISSUE TITLE
Client crashes on -mode when no mode is set

### ISSUE THREAD

**Issue by plachenko** [martynsmith/node-irc#454]
Hey,

I've been playing around with this and noticed that when I set -mode (-b for instance) on a non-banned client it crashes:

```
TypeError: Cannot read property 'filter' of undefined
    at chanModes (C:\Users\denny\Documents\node-irc\lib\irc.js:296:37)
    at C:\Users\denny\Documents\node-irc\lib\irc.js:315:25
    at Array.forEach (native)
    at Client.<anonymous> (C:\Users\denny\Documents\node-irc\lib\irc.js:266:26)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at iterator (C:\Users\denny\Documents\node-irc\lib\irc.js:842:26)
    at Array.forEach (native)
    at Socket.handleData (C:\Users\denny\Documents\node-irc\lib\irc.js:837:15)
    at emitOne (events.js:77:13)
```

I quickly scanned through the issues and PRs and the only thing related I could find is #177 which was a couple of years ago, but the code in question was implemented here 37b71db a few months ago. I looked through the code and implemented a fix (a check to see if channel.modeParams[mode] is of type undefined and skip any action) and I'll be submitting a PR shortly.

Thanks for this module!

**Comment by nlocnila** [comment]
+1
