### ISSUE TITLE
Error in 'raw': cannot read property 'filter' on undefined in chanModes

### ISSUE THREAD

**Issue by ra4king** [martynsmith/node-irc#472]
I received this error after a MODE -b event occurreed. It looks like channel.modeParams[mode] is undefined and the filter function call was made on it on [line 300 of irc.js] (https://github.com/martynsmith/node-irc/blob/3fde7c680a7578c8829ff117623f01f17155cee8/lib/irc.js#L300). I'm patching it.

**Comment by ra4king** [comment]
Patch: #473

**Comment by sh1omi** [comment]
I got the same error when removing quiet mask from a user.
The patch([#473](https://github.com/martynsmith/node-irc/pull/473)) fixed the issue.

**Comment by medikoo** [comment]
Happened also on my side:

```
TypeError: Cannot read property 'filter' of undefined
    at chanModes (/home/medyk/irc-notifier/node_modules/irc/lib/irc.js:296:37)
    at /home/medyk/irc-notifier/node_modules/irc/lib/irc.js:315:25
    at Array.forEach (native)
    at Client. (/home/medyk/irc-notifier/node_modules/irc/lib/irc.js:266:26)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at iterator (/home/medyk/irc-notifier/node_modules/irc/lib/irc.js:842:26)
    at Array.forEach (native)
    at Socket.handleData (/home/medyk/irc-notifier/node_modules/irc/lib/irc.js:837:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Any chance fix will land soon on npm?

**Comment by sh1omi** [comment]
@medikoo no one updating the node-irc, you will need to update it urself or download from someone.
You will need to change one line in irc.js https://github.com/sh1omi/node-irc/commit/fd0520a284ed5a13a33d7431d6baae063010fe2d

**Comment by medikoo** [comment]
@sh1omi you're trying to say that this project is no longer maintained? I don't see such info in main documentation.

**Comment by sh1omi** [comment]
@medikoo yes. :) the last commit is from "Mar 27, 2016".

**Comment by medikoo** [comment]
@martynsmith can you confirm?

**Comment by ssachtleben** [comment]
still happening :(

**Comment by jimjaeger** [comment]
Hi, the issue still happens. Any outlook for a fix?

**Comment by jimjaeger** [comment]
@martynsmith The issue still exists. Can you merge the fix into the master branch? Or what do you need to?
