### ISSUE TITLE
Install does not work on Debian stable.

### ISSUE THREAD

**Issue by ProgVal** [martynsmith/node-irc#475]
```
 npm install irc
npm WARN package.json skyweb@0.0.4 No repository field.
 
> node-icu-charset-detector@0.1.4 install /tmp/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

make: Entering directory '/tmp/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
In file included from ../node-icu-charset-detector.cpp:2:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
node-icu-charset-detector.target.mk:82: recipe for target 'Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o' failed
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory '/tmp/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> iconv@2.1.11 install /tmp/node_modules/irc/node_modules/iconv
> node-gyp rebuild

make: Entering directory '/tmp/node_modules/irc/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:0:
../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
iconv.target.mk:99: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory '/tmp/node_modules/irc/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/node_modules/irc/node_modules/iconv
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-icu-charset-detector@0.1.4
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing iconv@2.1.11
irc@0.5.0 node_modules/irc
└── irc-colors@1.3.0
 node -v
v0.10.29
 npm -v 
1.4.21
```

Note: despite the warning, it is not because of the name of the binary (I have a symlink to fix this issue).

**Comment by ProgVal** [comment]
Nevermind, it's not because of this lib, I should have read the errors more carefully.

**Comment by hdoedens** [comment]
@ProgVal I am having the same issue here. What was your solution?

**Comment by ProgVal** [comment]
@hdoedens http://stackoverflow.com/a/18130296/539465
