### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by alevshunov** [martynsmith/node-irc#514]
After few days of online:
Using NodeJS 4.4.7.

```
.../node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at chanModes (.../node_modules/irc/lib/irc.js:300:37)
    at .../node_modules/irc/lib/irc.js:319:25
    at Array.forEach (native)
    at Client.<anonymous> (.../node_modules/irc/lib/irc.js:270:26)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (.../node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (.../node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by WhoSoup** [comment]
Got this exact same error twice now. First one happened around two weeks into running, and now it just happened after about two days.

**Comment by GottZ** [comment]
there. have a proper exception report running on node v8.10.0:  
https://sentry.njgz.de/share/issue/d601a84d31c44559bcc1bd3d9d550016/

i think this project is dead anyways..

**Comment by KockaAdmiralac** [comment]
Got the same issue today, solved it by changing `[modeArg]` to `modeArg` in irc.js, line 319
