### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by thistehneisen** [martynsmith/node-irc#548]
```/home/influent/obql-bot/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'match' of undefined
    at Client.send (/home/influent/obql-bot/node_modules/irc/lib/irc.js:929:31)
    at Client.<anonymous> (/home/influent/obql-bot/bot.js:41:12)
    at Client.emit (events.js:193:13)
    at Client.<anonymous> (/home/influent/obql-bot/node_modules/irc/lib/irc.js:133:22)
    at Client.emit (events.js:193:13)
    at iterator (/home/influent/obql-bot/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (<anonymous>)
    at Socket.handleData (/home/influent/obql-bot/node_modules/irc/lib/irc.js:841:15)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)```

Haven't changed code much and this appeared whilst npm installing the library recently on different server.

**Comment by thistehneisen** [comment]
Note that this is on server with node v11.13.0, with v11.9.0 it's working fine
